# Generated by Django 5.1.6 on 2025-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobFinder", "0002_item_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("salary", models.CharField(blank=True, max_length=50, null=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
